name: jsAction
description: calculator to test js actions
inputs: 
  number1:
    required: true
    default: 0
  number2:
    required: true
    default: 0
outputs: 
  result:
    description: 'output of the sum'
runs:
  using: 'node20'
  main: 'dist/index.js'
      
