name: jsAction
description: calculator to test js actions
inputs: 
  number1:
    required: true
    default: 0
  number2:
    required: true
    default: 0
outputs: 
  result:
runs:
  using: 'node20'
  main: 'index.js'
      